services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nest-app-dev
    environment:
      - PORT=${PORT}
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    depends_on:
      - postgresql
      - redis
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./src:/app/src
    networks:
      - app-network
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./package-lock.json
        - action: rebuild
          path: ./prisma
