services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app-prod
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    depends_on:
      - postgresql
      - redis
    networks:
      - app-network
