FROM node:22-alpine

# Use apk for Alpine Linux to install postgresql-client
RUN apk add --no-cache postgresql-client

WORKDIR /app

COPY package*.json ./

# Install dependencies
RUN npm install --frozen-lockfile

COPY . .

EXPOSE 3000

COPY entrypoint.dev.sh /app/entrypoint.dev.sh
RUN chmod +x /app/entrypoint.dev.sh

CMD ["/app/entrypoint.dev.sh"]
