# @import .env.http
# @ref dev


{{
const fs = require('fs');
const path = './.state/auth.json';
let state = {};

if (fs.existsSync(path)) state = JSON.parse(fs.readFileSync(path, 'utf8'));

exports.state = state.data

}}

###
POST /api/v1/public/urls/shorten
Host: {{host}}
Accept: application/json
Content-Type: application/json

{
  "originalUrl": "https://tamamhuda.dev"
}

###
GET /api/v1/public/urls/shorten
Host: {{host}}
Accept: application/json
Content-Type: application/json

{
  "originalUrl": "https://tamamhuda.dev"
}


###
POST /api/v1/urls
Host: {{host}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{state.tokens.accessToken}}
{
  "originalUrl": "https://tamamhuda.dev",
  "channelIds": ["81100e9e-61f2-4b47-add6-5e79b2b2e080"]
}
