# @import .env.http
# @ref dev


{{
const fs = require('fs');
const path = './.state/auth.json';
let state = {};

if (fs.existsSync(path)) state = JSON.parse(fs.readFileSync(path, 'utf8'));

exports.state = state.data

}}

###
GET /api/v1/user/me
Host: {{host}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{state.tokens.accessToken}}


###

PUT /api/v1/user/update/{{state.user.id}}
Host: {{host}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{state.tokens.accessToken}}

{
    "fullName": "John Doe Update"
}
