export const SEND_MAIL_VERIFY_QUEUE = 'SEND_MAIL_VERIFY_QUEUE';
export const URL_ANALYTIC_QUEUE = 'URL_ANALYTIC_QUEUE';
export const URL_METADATA_QUEUE = 'URL_METADATA_QUEUE';
export const SEND_MAIL_SUBSCRIPTION_QUEUE = 'SEND_MAIL_SUBSCRIPTION_QUEUE';
export const SEND_MAIL_RESET_PASSWORD_QUEUE = 'SEND_MAIL_RESET_PASSWORD_QUEUE';
