export enum CachePrefix {
  APP = 'APP',
  USER = 'USER',
  SESSION = 'SESSION',
  ACCOUNT = 'ACCOUNT',
  URL_ANALYTICS = 'URL_ANALYTICS',
  IP_GEOLOCATION = 'IP_GEOLOCATION',
  URL_METADATA = 'URL_METADATA',
  THROTTLE = 'THROTTLE',
}
