export enum SubscriptionEndReason {
  COMPLETED = 'COMPLETED',
  CANCELLED_BY_USER = 'CANCELLED_BY_USER',
  CANCELLED_BY_ADMIN = 'CANCELLED_BY_ADMIN',
  EXPIRED_PAYMENT_FAILED = 'EXPIRED_PAYMENT_FAILED',
  EXPIRED_LINK = 'EXPIRED_LINK',
  TRIAL_EXPIRED = 'TRIAL_EXPIRED',
  UPGRADED = 'UPGRADED',
}
